# Generated by Django 3.0.8 on 2020-10-27 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201026_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='target',
        ),
        migrations.AddField(
            model_name='profile',
            name='followee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
