# Generated by Django 3.0.8 on 2020-11-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201027_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heart',
            field=models.IntegerField(),
        ),
    ]
