# Generated by Django 3.0.8 on 2020-11-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20201104_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='postid',
            field=models.IntegerField(),
        ),
    ]
