# Generated by Django 3.0.8 on 2020-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20201105_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='likers', to='network.post'),
        ),
        migrations.DeleteModel(
            name='like',
        ),
    ]
