# Generated by Django 3.0.8 on 2020-10-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201001_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createlisting', to='auctions.createlisting'),
        ),
    ]
