# Generated by Django 3.0.8 on 2020-10-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listingid',
        ),
    ]
