# Generated by Django 3.0.8 on 2020-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_closebid'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
